# Generated by Django 6.1.1 on 2026-09-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_envio', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('conductor', models.CharField(blank=True, max_length=200)),
                ('patente_vehiculo', models.CharField(blank=True, max_length=10)),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('preparacion', 'En Preparación'), ('despachado', 'Despachado'), ('transito', 'En Tránsito'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='preparacion', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso'), ('desvio', 'Desvío'), ('mecanica', 'Contingencia Mecánica'), ('danio', 'Daño'), ('otra', 'Otra')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='courier.envio')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=10)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviada', models.BooleanField(default=False)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='courier.envio')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='courier.paquete'),
        ),
        migrations.AddField(
            model_name='envio',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_destino', to='courier.sucursal'),
        ),
        migrations.AddField(
            model_name='envio',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_origen', to='courier.sucursal'),
        ),
    ]
